language: python
dist: xenial
python:
  - "2.7"
  - "3.5"

cache:
  pip: true

env:
  matrix:
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release CMAKE_C_COMPILER=clang CMAKE_CXX_COMPILER=clang++
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug CMAKE_C_COMPILER=clang CMAKE_CXX_COMPILER=clang++
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release CMAKE_C_COMPILER=gcc CMAKE_CXX_COMPILER=g++
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug CMAKE_C_COMPILER=gcc CMAKE_CXX_COMPILER=g++
  - TEST_SUITE=benchmark

matrix:
  include:
    - env: TEST_SUITE=cppcheck

addons:
  apt:
    packages:
      - python-dev
      - python-numpy
      - valgrind
      - cppcheck
      - memcached
      - libmemcached11
      - golang

install:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install future; fi
  - if [[ $TEST_SUITE = "unittest" ]]; then pip install pytest greenify gevent; fi
  - if [[ $TEST_SUITE = "benchmark" ]]; then pip install python-memcached pylibmc; fi

before_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server start; fi

script:
  - if [[ $CMAKE_C_COMPILER = "gcc" ]]; then export CC=gcc CXX=g++; fi
  - if [[ $CMAKE_C_COMPILER = "clang" ]]; then export CC=clang CXX=clang++; fi
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server stop; fi

deploy:
  provider: pypi
  skip_existing: true
  user: yangxiufeng
  password:
    secure: Oc2qdGCFGP5W51RcdD25q0hJx1mUOWf65ph8/T7hW2N4bjz2TJPsLvf37MNi5aHum0Kvqxo6HNEn3Ea+nqL9KgjxhnjmqSezwqxpXJrHgnqPMAH7prfpPpJW9R0h3PJDutMNmhsL2xn9NJeb6LQ+y38j44n1pN2JW3t2Z3CJavA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: douban/libmc
    branch: master
