language: python
python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7/lib/python2.7/site-packages
    - $HOME/virtualenv/python3.5/lib/python3.5/site-packages

env:
  matrix:
  - TEST_SUITE=cppcheck
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=clang MC_USE_PLOG=false
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=clang MC_USE_PLOG=false
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=gcc MC_USE_PLOG=false
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=gcc MC_USE_PLOG=false
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=clang MC_USE_PLOG=true
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=clang MC_USE_PLOG=true
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=gcc MC_USE_PLOG=true
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=gcc MC_USE_PLOG=true
  - TEST_SUITE=benchmark

addons:
  apt:
    packages:
      - python-dev
      - python-numpy
      - valgrind
      - cppcheck
      - memcached
      - libmemcached10
      - golang

install:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install future; fi
  - if [[ $TEST_SUITE = "unittest" ]]; then pip install pytest greenify gevent; fi
  - if [[ $TEST_SUITE = "benchmark" ]]; then pip install python-memcached pylibmc; fi

before_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server start; fi

script:
  - if [[ $PRJ_COMPILER = "gcc" ]]; then export CC=gcc CXX=g++; fi
  - if [[ $PRJ_COMPILER = "clang" ]]; then export CC=clang CXX=clang++; fi
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server stop; fi

deploy:
  provider: pypi
  user: yangxiufeng
  password:
    secure: Oc2qdGCFGP5W51RcdD25q0hJx1mUOWf65ph8/T7hW2N4bjz2TJPsLvf37MNi5aHum0Kvqxo6HNEn3Ea+nqL9KgjxhnjmqSezwqxpXJrHgnqPMAH7prfpPpJW9R0h3PJDutMNmhsL2xn9NJeb6LQ+y38j44n1pN2JW3t2Z3CJavA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: douban/libmc
    branch: master
