language: python
python:
  - "2.7"
  - "3.5"

cache:
  pip: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

env:
  matrix:
  - TEST_SUITE=cppcheck
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug
  - TEST_SUITE=benchmark

addons:
  apt:
    packages:
      - python-dev
      - python-numpy
      - valgrind
      - cppcheck
      - memcached
      - libmemcached10
      - golang

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install future; fi
  - if [[ $TEST_SUITE = "unittest" ]]; then pip install pytest greenify gevent; fi
  - if [[ $TEST_SUITE = "benchmark" ]]; then pip install python-memcached pylibmc; fi

before_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server start; fi

script:
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server stop; fi

deploy:
  provider: pypi
  skip_existing: true
  user: yangxiufeng
  password:
    secure: Oc2qdGCFGP5W51RcdD25q0hJx1mUOWf65ph8/T7hW2N4bjz2TJPsLvf37MNi5aHum0Kvqxo6HNEn3Ea+nqL9KgjxhnjmqSezwqxpXJrHgnqPMAH7prfpPpJW9R0h3PJDutMNmhsL2xn9NJeb6LQ+y38j44n1pN2JW3t2Z3CJavA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: douban/libmc
    branch: master
